### ISSUE TITLE
Simplify the Chakra UI Discord

### ISSUE THREAD

**Issue by aaronmcadam** [chakra-ui/rfcs#2]
The Discord has a couple of problems with its layout. The amount of channels causes a few issues:
- People are confused about where to post messages
- People post the same messages in multiple channels
- As somebody looking to help others, it's tough to find messages from people who need help
- Having topic-specific channels like we do fracture conversations into too fine-grained buckets, so those interested in different topics aren't seeing those conversations.

### Proposed solution
The following shows the current channel structure and proposes a new one.

#### Current structure
- WELCOME
	- introductions
	- rules
- COLLABORATORS (REACT)
	- rules
	- general
	- playground
	- devrel
	- docs
	- triage
- GENERAL CHANNELS
	- general
	- announcements
	- events
	- showcase
	- code-review
	- jobs
	- roadmap
- REACT
	- react-18
	- need-help
	- v0-migration
	- documentation
	- testing
	- api-idea
	- questions
- DESIGN
	- general
- VUE
	- vue-announcements
	- vue-general
	- vue-questions
	- vue-showcase
	- vue-api-discussion
	- vue-documentation
	- vue-accessibility
	- vue-3-discussions
	- meeting-room
- HELP (VUE)
	- how-to-get-help
	- vue-need-help

#### Proposed structure
- WELCOME
	- introductions
	- rules
- COLLABORATORS (REACT)
	- rules
	- general
	- playground
	- devrel
	- docs
	- triage
- GENERAL CHANNELS
	- general
	- announcements
	- events
	- showcase
	- jobs
	- roadmap
	- design
- REACT
	- react-18
	- help
- VUE
	- vue-announcements
	- vue-general
	- vue-questions
	- vue-showcase
	- vue-api-discussion
	- vue-documentation
	- vue-accessibility
	- vue-3-discussions
	- meeting-room
- HELP (VUE)
	- how-to-get-help
	- vue-need-help

**Comment by nikolovlazar** [comment]
This structure makes sense to me. Let's leave some time for the others to check it as well, and at the end of the week if there are no issues I can apply the changes. Thanks for working on this, @aaronmcadam!

**Comment by segunadebayo** [comment]
I've applied most of these changes. Thanks Aaron
